#!/bin/bash

TFTP=/srv/tftp
ROOT=/srv/nfs/pandaroot

sudo mkdir -p $ROOT

echo "Removing preivous root image from '$ROOT' ..."
sudo rm -rf $ROOT/*

FIRMWARE=$ROOT/lib/firmware

echo "Copying firmware to '$FIRMWARE' ..."
sudo mkdir -p $FIRMWARE
sudo cp -v htc_9271.fw $FIRMWARE

echo "Copying kernel image to TFTP '$TFTP' ..."
sudo cp -v output/images/uImage $TFTP

echo "Extracting root image to '$ROOT' ..."
sudo tar -C $ROOT/ -xf output/images/rootfs.tar

echo "Done"
