#!/bin/sh

die() { echo "ERROR: $@"; exit 1; }

IFACE=wlan0
SSID=cozyguest
PINGHOST=google.com

iw reg 'set' US

echo "Brining up '$IFACE'..."
ip link 'set' dev $IFACE up || die "Failed to bring up interface '$IFACE'"

echo "Connecting '$IFACE' to SSID '$SSID'..."
iw $IFACE connect -w $SSID || die "Failed to connect to SSID: $SSID"

echo "Issuing DHCP request for '$IFACE'..."
e=`udhcpc -i $IFACE 2>&1` || die "Failed to get IP address via DHCP:\n\n$e"

echo "Pinging $PINGHOST from '$IFACE'..."
e=`ping -c 1 $PINGHOST 2>&1` || die "Failed to ping host: $PINGHOST\n\n$e"

echo "Disconnecting '$IFACE' from SSID '$SSID'..."
iw $IFACE disconnect || die "Failed to disconnect from SSID: $SSID"

echo "Brining down '$IFACE'..."
ip link 'set' dev $IFACE down || die "Failed to bring interface '$IFACE' down"

echo
echo SUCCESS
echo
