#!/bin/bash

source `dirname $0`/common.sh

h1 "Press <enter> to attach to pandaboard console (press CTRL-A K, to exit)..."
h2 "Login with test (empty password) or root (no password)"

read

if sudo screen -ls $SCREEN_NAME | grep $SCREEN_NAME 2>/dev/null; then
    sudo screen -rd $SCREEN_NAME
    exit 0
fi

sudo screen -S $SCREEN_NAME $(find_usb_serial) 115200
