#!/bin/bash

source `dirname $0`/common.sh

usage() {
cat << EOF
usage: $0 [<OPTIONS>]

Build buildroot, invokes scripts/gen_rootfs to push rootfs to:
    \t${NFS_ROOT}

And the kernel to:
    \t${TFTP_ROOT}/uImage

OPTIONS:
   -v         Be verbose.
   -r         Rebuild linux
   -h         Show this message.
EOF
}

if [[ -z $UNDER_INSTALL_SH ]]; then
    while getopts "rckChvfd:" options; do
        case $options in
        v ) VERBOSE=1;;
        h ) usage; exit 0;;
        r ) REBUILD=1;;
        * ) echo unkown option: ${option}
            usage; exit 1;;
        esac
    done
fi

_pushd $BUILDROOT

if [[ -n $REBUILD ]]; then
    rm -f output/build/linux-ft-sd8787-driver/.stamp_{built,images_installed,target_installed,configured}
fi

start_spinner "Building buildroot..."
Qorerr make || die "Make failed"

_popd
