#!/bin/bash

source `dirname $0`/common.sh

T=$BUILDROOT/output/build/linux-ft-sd8787-driver/.config

cp $CONF/linux.config $T && (cd $BUILDROOT && make linux-menuconfig) \
    && cp $T $CONF/linux.config \
    && sleep_touch $CONF/linux.config && $SCRIPTS/patch_buildroot
