#!/bin/bash

source `dirname $0`/common.sh

WIRESHARK_VER=1.10.0
WIRESHARK_MK=$BUILDROOT/package/wireshark/wireshark.mk

echo "Wireshark makefile: $WIRESHARK_MK"

if ! grep "WIRESHARK_VERSION.*$WIRESHARK_VER" $WIRESHARK_MK &>/dev/null; then
    echo "Updating wireshark version to $WIRESHARK_VER"
    sed -i "s/\(WIRESHARK_VERSION = \).*/\1$WIRESHARK_VER/" $WIRESHARK_MK
fi

PATTERN="source.*[\"]package/python-scapy/Config[.]in[\"]"
LINE="source \"package/python-scapy/Config.in\""
CFG=$BUILDROOT/package/Config.in

echo "Package config: $CFG"

if ! grep $PATTERN $CFG &>/dev/null; then
    echo "Adding python-scapy to main config..."
    echo       >>$CFG
    echo $LINE >>$CFG
fi

D=package/python-scapy
[ -e "$D" ] || mkdir -vp $D

update_if_newer() {
    local src=$1
    local dst=$2
    if [[ $src -nt $dst ]]; then
        echo "Updating $dst..."
        cp -vf $src $dst
    fi
}

update_if_newer $CONF/buildroot.config $BUILDROOT/.config

SCAPY_CFG_SRC=$CONF/scapy_Config.in
SCAPY_CFG_DST=$D/Config.in

update_if_newer $SCAPY_CFG_SRC $SCAPY_CFG_DST

SCAPY_MAKEFILE_NAME=python-scapy.mk
SCAPY_MAKEFILE_SRC=$CONF/$SCAPY_MAKEFILE_NAME
SCAPY_MAKEFILE_DST=$D/$SCAPY_MAKEFILE_NAME

update_if_newer $SCAPY_MAKEFILE_SRC $SCAPY_MAKEFILE_DST
